"""Tests for textual alternatives generated by Ollama."""

from types import SimpleNamespace

from rouen_ocr import textual_alternative


def test_alt_image_returns_model_content(monkeypatch) -> None:
    """The model response content is returned as the textual alternative."""
    image = b"image bytes"
    expected = "Description de l'image."

    def fake_chat(**kwargs: object) -> SimpleNamespace:
        assert kwargs == {
            "model": textual_alternative.ALT_MODEL,
            "messages": [
                {
                    "role": "user",
                    "content": textual_alternative.ALT_BASE_PROMPT,
                    "images": [image],
                }
            ],
            "options": {
                "temperature": 0.0,
                "top_p": 0.1,
                "num_ctx": 16384,
                "num_predict": 16384,
                "repeat_penalty": 1.0,
                "seed": 0,
            },
            "think": False,
        }
        return SimpleNamespace(
            message=SimpleNamespace(content=expected)
        )

    monkeypatch.setattr(textual_alternative, "chat", fake_chat)

    assert textual_alternative.alt_image(image) == expected
